### ISSUE TITLE
Issue with BLE device name in SPBTLE Sensor demo ino

### ISSUE THREAD

**Issue by escodam** [stm32duino/SPBTLE-RF#6]
Hello, When I change device name in the SPBTLE Sensor demo example, nothing change.
The device name seems rewrited by another funct.

Thanks and regards

**Comment by fpistm** [comment]
Hi @escodam,
thanks for the issue.
@cparata could you have a look on this?

**Comment by cparata** [comment]
Hi @escodam and @fpistm, unfortunately it is a known bug. I did not develop the library, so I'm not so expert to fix it. Anyway, as I know, the SensorDemo class should be in the application code instead in the library code. You can give a look at the NucleoCar sketch available on FP_Examples. There, I was able to give a different name to the BlueNRG device defining NucleoCarServiceClass in the application code and defining a new name in the setConnectable. It was a workaround that I found that can be used also in other examples. This library needs surely a rework, but at the moment I do not have time to work on it. Regards
