### ISSUE TITLE
Unable to Connect 

### ISSUE THREAD

**Issue by jacklu333333** [stm32duino/SPBTLE-RF#8]
Hi, 
I use my mobile phone model Google Pixel 3 tried to connect to the stm32L475 which has this module onboard and I tried to test SensorDemo. Every time it keeps ask me for the pin code which supposed to be 0000 or 1234 but neither works. Please help me. Thanks
Regards, 
Jack Lu

**Comment by cparata** [comment]
Hi @jacklu333333 ,
could you try with 123456? The pin is passed in the "aci_gap_set_auth_requirement" API that you can find in the sensor_service.cpp.
If you are familiar with ArduinoBLE, you can also give a try to the STM32duinoBLE library that should work also for IoT disco board.
Best Regards,
Carlo

**Comment by jacklu333333** [comment]
Hi, 
Sorry for not looking into it carefully. Silly me and thanks a lot. It works
Regards,
Jack Lu
